name: scissors
version: 0.1.0
description: A CSS minifier / tree-shaker for AngularDart 1.x / Angular2.
authors:
- Olivier Chafik <ochafik@google.com>
homepage: http://github.com/google/dart-scissors
dependencies:
  barback: ">=0.15.0 <0.16.0"
  code_transformers: ">=0.2.3 <0.3.0"
  csslib: ">=0.12.0 <0.13.0"
  html: ">=0.12.0 <0.13.0"
  quiver: ">=0.21.0 <0.22.0"
  source_maps: ">=0.10.0 <0.11.0"
  path: ">=1.3.0 <2.0.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  unittest: ">=0.11.0 <0.12.0"
