name: scissors_angular1_example
version: 0.1.3
dependencies:
  angular: "1.1.0"
dev_dependencies:
  # scissors: 0.1.3
  scissors: {path: ../..}
  dart_to_js_script_rewriter: ^0.1.0
transformers:
# Use this transformer instead to force-build all the css files upfront:
# - scissors/eager_transformer
- scissors:
    verbose: true
    # sasscPath: path/to/sassc
    # sasscArgs:
    #   - -foo
    #   - -bar
- angular
- dart_to_js_script_rewriter
