name: scissors_angular1_example
version: 0.1.2
dependencies:
  angular: "1.1.0"
dev_dependencies:
  scissors: 0.1.2
transformers:
- scissors:
    verbose: true
# - scissors:
#     sasscPath: path/to/sassc
#     sasscArgs:
#       - -foo
#       - -bar
