name: scissors_angular1_example
version: 0.1.0
dependencies:
  angular: "1.1.0"
dev_dependencies:
  scissors: 0.1.1
transformers:
- scissors
# - scissors:
#     sasscPath: path/to/sassc
#     sasscArgs:
#       - -foo
#       - -bar
